### ISSUE TITLE
Cannot open jpg despite having pymaging-jpg installed

### ISSUE THREAD

**Issue by pr1001** [ojii/pymaging#29]
I get the following:

```
>>> from pymaging.image import Image
>>> img_part = Image.open_from_path('spheres/peter5/images/peter5_0_0_0.jpg')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/pymaging/pymaging/image.py", line 62, in open_from_path
    return cls.open(fobj)
  File "src/pymaging/pymaging/image.py", line 57, in open
    raise FormatNotSupported()
pymaging.exceptions.FormatNotSupported
```

**Comment by ojii** [comment]
Hi @pr1001,

Unfortunately pymaging-jpg is currently not in a very stable state. It can open some JPG files, but not all, and those it can open get distorted.

However to see if your installation is correct, try the following:

``` python
from pymaging_jpg.jpg import decode

with open('spheres/peter5/images/peter5_0_0_0.jpg') as fobj:
    image = decode(fobj)
```

If that works, there's an issue with your installation, if it doesn't, pymaging-jpg fails to decode your image.

**Comment by pr1001** [comment]
Wow, that's a fast response! This is what I get:

```
>>> from pymaging_jpg.jpg import decode
>>> with open('spheres/peter5/images/peter5_0_0_0.jpg') as fobj:
...     image = decode(fobj)
... 
>>> image
>>> print(image)
None
```

**Comment by ojii** [comment]
Okay pymaging-jpg fails to decode the file then. Could you open a ticket on https://github.com/ojii/pymaging-jpg and upload the jpg file?

**Comment by pr1001** [comment]
Sure, thanks! In the meantime I can convert my images to PNG using `sips` before processing...
